<!DOCTYPE html><html lang=es data-bs-theme=dark><link rel=stylesheet href=EduardoHerreraForero.f3ce418f.css><meta charset=utf-8><meta name=viewport content="width=device-width, initial-scale=1"><meta name=description content="Descubre los fundamentos de excepciones en Python: gestión de errores desde el punto de vista de Programación Orientada a Objetos para código robusto."><meta name=title content="POO: Excepciones Python 3 - Ing. Eduardo Herrera Forero."><meta name=author content="Ing. Eduardo Herrera Forero"><meta name=application-name content=EHF><meta name=robots content="index, follow"><link rel=canonical href=https://eduardoherreraf.github.io/cursoPython3-0706_poo_excepciones.html><meta property=og:type content=website><meta property=og:title content="POO: Excepciones Python 3 - Ing. Eduardo Herrera Forero."><meta property=og:description content="Descubre los fundamentos de excepciones en Python: gestión de errores desde el punto de vista de Programación Orientada a Objetos para código robusto."><meta property=og:image content=https://i.imgur.com/JKbKYrO.png><meta property=og:image:alt content="Logo del ingeniero Eduardo Herrera Forero"><meta property=og:url content=https://eduardoherreraf.github.io/cursoPython3-0706_poo_excepciones.html><meta property=og:locale content=es_CO><meta name=twitter:card content=summary><meta name=twitter:title content="POO: Excepciones Python 3 - Ing. Eduardo Herrera Forero."><meta name=twitter:description content="Descubre los fundamentos de excepciones en Python: gestión de errores desde el punto de vista de Programación Orientada a Objetos para código robusto."><meta name=twitter:image content=https://i.imgur.com/JKbKYrO.png><meta name=twitter:image:alt content="Logo del ingeniero Eduardo Herrera Forero"><meta name=twitter:url content=https://eduardoherreraf.github.io/cursoPython3-0706_poo_excepciones.html><meta name=twitter:site content=@ehfeduardo><link rel=apple-touch-icon sizes=180x180 href=apple-touch-icon.96046c77.png><link rel=icon type=image/png sizes=32x32 href=favicon-32x32.f7991d03.png><link rel=icon type=image/png sizes=192x192 href=android-chrome-192x192.4500461c.png><link rel=icon type=image/png sizes=16x16 href=favicon-16x16.060ee0ac.png><link rel=manifest href=site.webmanifest><link rel=mask-icon href=safari-pinned-tab.df3b9c22.svg color=#5bbad5><meta name=msapplication-TileColor content=#da532c><meta name=theme-color content=#ffffff><title>POO: Excepciones Python 3 - Ing. Eduardo Herrera Forero.</title><script type=module src=EduardoHerreraForero.b1453780.js></script><meta name=google-site-verification content=2H5ZMCD1_xl7oxaiqnopfdQBnIXVIOfmW0UBSa5sQJc><body>
  
  <nav class="border border-1 fixed-top nav-underline navbar navbar-expand-lg">
    <div class=container-fluid>
      
      <a class="align-items-center d-flex ms-2 navbar-brand" href=index.html>
        <img src=logo.08948a42.png alt="Logo de Ing. Eduardo Herrera Forero" width=30 height=30 class="align-text-top d-inline-block me-1">
        <span class="d-lg-inline d-none">Ing. Eduardo Herrera Forero</span>
      </a>
      
      <button class=navbar-toggler type=button data-bs-toggle=collapse data-bs-target=#navbarSupportedContent aria-controls=navbarSupportedContent aria-expanded=false aria-label="Toggle navigation">
        <span class=navbar-toggler-icon></span>
      </button>
      
      <div class="collapse ms-auto navbar-collapse text-center" id=navbarSupportedContent>
        <ul class="justify-content-lg-end mb-2 mb-lg-0 ms-auto navbar-nav w-100">
          <li class=nav-item>
            <a class="mx-1 nav-link" href=index.html>SOBRE MÍ</a>
          </li>
          <li class=nav-item>
            <a class="mx-1 nav-link" href=index.html#resume>EXPERIENCIA</a>
          </li>
          <li class=nav-item>
            <a class="mx-1 nav-link" href=index.html#portfolio>PORTAFOLIO</a>
          </li>
          <li class=nav-item>
            <a class="mx-1 nav-link" href=index.html#studies>ESTUDIOS</a>
          </li>
          <li class=nav-item>
            <a class="mx-1 nav-link publicaciones-activo" href=index.html#blog>PUBLICACIONES</a>
          </li>
          <li class=nav-item>
            <a class="mx-1 nav-link" href=index.html#contact>CONTACTO</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  

  
  <div class=container-fluid id=introduccion>
    <main class=row>
      <section class="col-lg-9 pb-3 pt-5 px-lg-4">
        
        <article class="border-1 border-bottom pb-3 row" data-bs-spy=scroll data-bs-target=#list-example data-bs-smooth-scroll=true>
          <div>
            <header>
              <h1>POO: Excepciones en Python</h1>
            </header>

            
            <div class=mt-5>
              <h2>Introducción</h2>
              <p>
                Las excepciones en Python son un mecanismo para manejar
                errores y otros eventos inesperados que pueden ocurrir durante
                la ejecución de un programa. En la programación orientada a
                objetos (POO), las excepciones permiten que los objetos
                manejen errores de manera más estructurada y controlada
              </p>
              <div class="centrar-imagen imagen50">
                <figure>
                  <img src=https://i.ibb.co/1f9pbDg/poexcepciones.jpg class=img-fluid alt="POO: Excepciones en Python  " title="¿Cómo manejar una excepción en Python?">
                  <figcaption>POO: Excepciones en Python</figcaption>
                </figure>
              </div>
            </div>
            
            <div id=teoria-basica-de-excepciones-clasicas class=mt-5>
              <h2>Teoría Básica de Excepciones Clásicas</h2>
              <p>
                Una excepción es un evento que interrumpe el flujo normal de
                un programa. Esto puede ocurrir debido a errores como:
              </p>
              <ul>
                <li>Intentar dividir entre cero.</li>
                <li>Acceder a un índice fuera de rango en una lista.</li>
                <li>Operar sobre un archivo que no existe.</li>
              </ul>
              <p>
                En Python, las excepciones son objetos derivados de la clase
                base <code class=language-python>BaseException</code>, lo
                que refuerza su integración con la POO.
              </p>
              <p>
                Las excepciones pueden ser manejadas utilizando bloques
                <code class=language-python>try</code>,
                <code class=language-python>except</code>,
                <code class=language-python>else</code> y
                <code class=language-python>finally</code>. A continuación,
                se explica cada uno de estos bloques con un ejemplo:
              </p>
              <ul>
                <li>
                  <span class=fw-bold><code class=language-python>try</code></span>: Este bloque contiene el código
                  que puede generar una
                  excepción.
                </li>
                <li>
                  <span class=fw-bold><code class=language-python>except</code></span>: Este bloque maneja la
                  excepción que se genera en el
                  bloque <code class=language-python>try</code>. Puedes
                  tener múltiples bloques
                  <code class=language-python>except</code> para manejar
                  diferentes tipos de excepciones.
                </li>
                <li>
                  <span class=fw-bold><code class=language-python>else</code></span>: Este bloque se ejecuta si no
                  se genera ninguna excepción
                  en el bloque <code class=language-python>try</code>.
                </li>
                <li>
                  <span class=fw-bold><code class=language-python>finally</code></span>: Este bloque se ejecuta
                  siempre, independientemente de si
                  se generó una excepción o no.
                </li>
              </ul>
              <p>Ejemplo que ilustra el uso de estos bloques:</p>
              <div class=ej-sintaxis>
                <pre data-src-status=loaded tabindex=0>                    <code class=language-python data-prismjs-copy=Copy>
                      def dividir_numeros(a, b):
                          try:
                              # Intentamos dividir a entre b
                              resultado = a / b
                          except ZeroDivisionError as e:
                              # Manejamos la excepción de división por cero
                              print(f"Error: {e}")
                              return None
                          except TypeError as e:
                              # Manejamos la excepción de tipo incorrecto
                              print(f"Error: {e}")
                              return None
                          else:
                              # Este bloque se ejecuta si no hay excepciones
                              print("La división se realizó con éxito.")
                              return resultado
                          finally:
                              # Este bloque se ejecuta siempre
                              print("Ejecución del bloque finally.")
                      # Ejemplos de uso
                      print(dividir_numeros(10, 2))    # Debería imprimir "La división se realizó con éxito." y luego "Ejecución del bloque finally."
                      print(dividir_numeros(10, 0))    # Debería imprimir "Error: division by zero" y luego "Ejecución del bloque finally."
                      print(dividir_numeros(10, 'a'))  # Debería imprimir "Error: unsupported operand type(s) for /: 'int' and 'str'" y luego "Ejecución del bloque finally."
                    </code>
                </pre>
              </div>
            </div>
            
            
            <div id=las-excepciones-son-clases class=mt-5>
              <h2>Las Excepciones Son Clases</h2>
              
              <div>
                <h3>Jerarquía de Excepciones</h3>
                <p>
                  Las excepciones en Python son implementadas como clases, y
                  todas las excepciones derivan de la clase base
                  <code class=language-python>BaseException</code>. La
                  mayoría de las excepciones que se encuentran en el uso
                  diario derivan de la clase
                  <code class=language-python>Exception</code>, que a su vez
                  es una subclase de
                  <code class=language-python>BaseException</code>.
                </p>
                <p>
                  Aquí hay una vista general de la jerarquía de excepciones en
                  Python:
                </p>
                <div class=ej-sintaxis>
                  <pre data-src-status=loaded tabindex=0>                      <code class=language-plaintext data-prismjs-copy=Copy>
                        BaseException
                        ├── Exception
                        │    ├── ArithmeticError
                        │    │    ├── FloatingPointError
                        │    │    ├── OverflowError
                        │    │    └── ZeroDivisionError
                        │    ├── AssertionError
                        │    ├── AttributeError
                        │    ├── BufferError
                        │    ├── EOFError
                        │    ├── ImportError
                        │    │    └── ModuleNotFoundError
                        │    ├── LookupError
                        │    │    ├── IndexError
                        │    │    └── KeyError
                        │    ├── MemoryError
                        │    ├── NameError
                        │    │    └── UnboundLocalError
                        │    ├── OSError
                        │    │    ├── BlockingIOError
                        │    │    ├── ChildProcessError
                        │    │    ├── ConnectionError
                        │    │    │    ├── BrokenPipeError
                        │    │    │    ├── ConnectionAbortedError
                        │    │    │    ├── ConnectionRefusedError
                        │    │    │    └── ConnectionResetError
                        │    │    ├── FileExistsError
                        │    │    ├── FileNotFoundError
                        │    │    ├── IsADirectoryError
                        │    │    ├── NotADirectoryError
                        │    │    ├── InterruptedError
                        │    │    ├── PermissionError
                        │    │    ├── ProcessLookupError
                        │    │    └── TimeoutError
                        │    ├── ReferenceError
                        │    ├── RuntimeError
                        │    │    ├── NotImplementedError
                        │    │    └── RecursionError
                        │    ├── StopIteration
                        │    ├── StopAsyncIteration
                        │    ├── SyntaxError
                        │    │    └── IndentationError
                        │    │         └── TabError
                        │    ├── SystemError
                        │    ├── TypeError
                        │    ├── ValueError
                        │    │    └── UnicodeError
                        │    │         ├── UnicodeDecodeError
                        │    │         ├── UnicodeEncodeError
                        │    │         └── UnicodeTranslateError
                        │    └── Warning
                        │         └── DeprecationWarning
                        │         └── PendingDeprecationWarning
                        │         └── RuntimeWarning
                        │         └── SyntaxWarning
                        │         └── UserWarning
                        │         └── FutureWarning
                        │         └── ImportWarning
                        │         └── UnicodeWarning
                        │         └── BytesWarning
                        │         └── ResourceWarning
                        ├── GeneratorExit
                        ├── KeyboardInterrupt
                        └── SystemExit
                      </code>
                    </pre>
                </div>
              </div>
              
              
              <div>
                <h3>Acceso a Atributos en Excepciones</h3>
                <p>
                  En Python, la palabra clave
                  <code class=language-python>as</code> se utiliza en el
                  contexto de manejo de excepciones para asignar una excepción
                  capturada a una variable. Esto permite acceder a la
                  información de la excepción, como su mensaje de error y
                  otros atributos, dentro del bloque
                  <code class=language-python>except</code>.
                </p>
                <p>Sintaxis Básica:</p>
                <div class=ej-sintaxis>
                  <pre data-src-status=loaded tabindex=0>                      <code class=language-python data-prismjs-copy=Copy>
                        try:
                            # Código que puede generar una excepción
                        except ExceptionType as variable:
                            # Manejo de la excepción utilizando la variable
                      </code>
                  </pre>
                </div>
                <p>Ejemplo básico:</p>
                <div class=ej-sintaxis>
                  <pre data-src-status=loaded tabindex=0>                      <code class=language-python data-prismjs-copy=Copy>
                        try:
                            resultado = 10 / 0  # Esto genera un ZeroDivisionError
                        except ZeroDivisionError as e:
                            print(f"Ha ocurrido un error: {e}")
                        # Salida: Ha ocurrido un error: division by zero
                      </code>
                    </pre>
                </div>
                <p>Desglose del código:</p>
                <ul>
                  <li>
                    <span class=fw-bold><code class=language-python>try</code></span>: Se intenta ejecutar el código
                    que podría generar un
                    error.
                  </li>
                  <li>
                    <span class=fw-bold><code class=language-python>except ZeroDivisionError as e</code></span>:
                    <ul>
                      <li>
                        Captura la excepción del tipo
                        <code class=language-python>ZeroDivisionError</code>.
                      </li>
                      <li>
                        Asigna la instancia de la excepción capturada a la
                        variable <code class=language-python>e</code>.
                      </li>
                    </ul>
                  </li>
                  <li>
                    <span class=fw-bold><code class=language-python>e</code></span>: Es una instancia de
                    <code class=language-python>ZeroDivisionError</code> y
                    contiene información adicional sobre el error, como el
                    mensaje de error.
                  </li>
                </ul>
              </div>
              
              
              <div>
                <h3>Acceso a Otros Atributos de la Excepción</h3>
                <p>
                  Algunas excepciones tienen atributos adicionales que puedes
                  acceder. Por ejemplo, la excepción
                  <code class=language-python>OSError</code> tiene un
                  atributo <code class=language-python>errno</code> que
                  contiene el número de error del sistema operativo:
                </p>
                <div class=ej-sintaxis>
                  <pre data-src-status=loaded tabindex=0>                      <code class=language-python data-prismjs-copy=Copy>
                        try:
                            with open('archivo_inexistente.txt', 'r') as file:
                                contenido = file.read()
                        except FileNotFoundError as e:
                            print(f"Error al abrir el archivo: {e}")
                            print(f"Número de error: {e.errno}")
                      </code>
                    </pre>
                </div>
              </div>
              
            </div>
            
            
            <div id=como-crear-una-excepcion-propia class=mt-5>
              <h2>Cómo Crear una Excepción Propia</h2>
              <p>
                Para crear una excepción propia en Python, se debe definir una
                nueva clase que herede de la clase base
                <code class=language-python>Exception</code>. Esta clase
                personalizada puede incluir métodos y atributos adicionales
                según sea necesario. A continuación, se presenta un ejemplo de
                cómo redactar una excepción propia en tercera persona.
              </p>
              <p>
                Primero, se define la clase de la excepción personalizada. En
                este ejemplo, se creará una excepción llamada
                <code class=language-python>MiExcepcionPersonalizada</code>:
              </p>
              <div class=ej-sintaxis>
                <pre data-src-status=loaded tabindex=0>                    <code class=language-python data-prismjs-copy=Copy>
                      # Definición de la excepción personalizada
                      class MiExcepcionPersonalizada(Exception):
                          """
                          Esta clase representa una excepción personalizada que se puede lanzar
                          cuando ocurre un error específico en el programa.
                          """
                          def __init__(self, mensaje):
                              """
                              Inicializa la excepción con un mensaje descriptivo del error.
                              :param mensaje: Un mensaje descriptivo del error.
                              """
                              super().__init__(mensaje)
                      # Función que puede lanzar la excepción personalizada
                      def funcion_que_puede_fallar(condicion):
                          """
                          Esta función lanza una excepción personalizada si se cumple una condición específica.
                          :param condicion: Una condición booleana que determina si se lanza la excepción.
                          :raises MiExcepcionPersonalizada: Si la condición es verdadera.
                          """
                          if condicion:
                              raise MiExcepcionPersonalizada("Ha ocurrido un error específico.")
                      # Uso de la excepción personalizada en un bloque try-except
                      try:
                          funcion_que_puede_fallar(True)
                      except MiExcepcionPersonalizada as e:
                          print(f"Se ha capturado una excepción: {e}")
                    </code>
                  </pre>
              </div>
              <p>En este ejemplo:</p>
              <ul>
                <li>
                  <span class=fw-bold>Definición de la Excepción Personalizada</span>:
                  <ul>
                    <li>
                      Se define una clase
                      <code class=language-python>MiExcepcionPersonalizada</code>
                      que hereda de Exception.
                    </li>
                    <li>
                      El método
                      <code class=language-python>__init__</code> se utiliza
                      para inicializar la excepción con un mensaje
                      descriptivo.
                    </li>
                  </ul>
                </li>
                <li>
                  <span class=fw-bold>Función que Puede Fallar</span>:
                  <ul>
                    <li>
                      Se define una función
                      <code class=language-python>funcion_que_puede_fallar</code>
                      que toma una condición booleana como argumento.
                    </li>
                    <li>
                      Si la condición es verdadera, la función lanza la
                      excepción personalizada con un mensaje específico.
                    </li>
                  </ul>
                </li>
                <li>
                  <span class=fw-bold>Uso de la Excepción Personalizada</span>:
                  <ul>
                    <li>
                      Se utiliza un bloque
                      <code class=language-python>try</code>-except para
                      llamar a la función
                      <code class=language-python>funcion_que_puede_fallar</code>
                      con una condición verdadera.
                    </li>
                    <li>
                      Si la excepción personalizada es lanzada, se captura y
                      se imprime un mensaje indicando que se ha capturado la
                      excepción.
                    </li>
                  </ul>
                </li>
              </ul>
            </div>
            
          </div>
        </article>
        
        
        <article class=row id=comments>
          <h2>COMENTARIOS</h2>
          <p>
            Si tiene alguna inquietud, duda o ha encontrado algún error, por
            favor infórmelo a través del formulario disponible para este
            propósito.
          </p>
          <div class="d-flex justify-content-center">
            <form action=https://formspree.io/f/mdkdawkg method=post id=myForm>
              <fieldset class="d-flex flex-column gap-3">
                <legend class="fs-4 text-center">Deje su comentario</legend>

                <div class="d-flex flex-column">
                  <label for=name>Nombre:</label>
                  <input name=name id=name placeholder=User class="form-control rounded" required>
                </div>

                <div class="d-flex flex-column">
                  <label for=email>Email:</label>
                  <input type=email name=email id=email placeholder=user@mail.com class="form-control rounded" required>
                </div>

                <div class="d-flex flex-column">
                  <label for=message>Mensaje:</label>
                  <textarea name=message id=message cols=30 rows=5 placeholder="Su comentario..." class="form-control rounded-3" required></textarea>
                </div>

                <button class="border border-2 btn btn-outline-light my-3 rounded-pill">
                  Enviar
                </button>
              </fieldset>

              <p class="small text-center">
                La política de privacidad, y los términos y condiciones están
                disponibles en el formulario de contacto.
              </p>
            </form>
          </div>
        </article>
        
      </section>

      
      <aside class="col-lg-3 d-lg-block d-none">
        <h2>En Este Artículo</h2>
        <div class=menu-scroll>
          <div class=menu-container>
            <div class="border border-1">
              <div class=menu-item><a href=#introduccion class=simple-link>Introducción</a></div>
              <div class=menu-item><a href=#teoria-basica-de-excepciones-clasicas class=simple-link>Teoría Básica
                  de Excepciones Clásicas</a></div>
              <div class=menu-item><a href=#las-excepciones-son-clases class=simple-link>Las Excepciones Son
                  Clases</a></div>
              <div class=menu-item><a href=#como-crear-una-excepcion-propia class=simple-link>Cómo Crear una
                  Excepción Propia</a></div>
              
              <div class=menu-item><a href=#comments class=simple-link>Comentarios</a></div>
            </div>
          </div>
        </div>
      </aside>
    </main>
    

  </div>
  
  
  <footer class="border-1 border-top m-1 mt-auto row">
    <div class=row>
      
      <address class="align-items-center col-lg-4 d-flex flex-column">
        <div class="fs-2 text-center">Contacto</div>
        <div class="align-items-center d-flex flex-row">
          <i class="bi bi-envelope-at fs-3"></i>
          <span class=ms-3>
            <a class=text-decoration-none href=mailto:ehfeduardo@gmail.com>ehfeduardo@gmail.com</a>
          </span>
        </div>
        <div class="align-items-center d-flex flex-row">
          <i class="bi bi-geo-alt fs-3"></i>
          <span class=ms-3>Bogotá D. C. - Colombia</span>
        </div>
      </address>
      
      <div class="align-items-center col-lg-4 d-flex flex-column h-100 justify-content-center">
        <div>
          <i class="bi bi-c-circle fs-5"></i>
        </div>
        <div class=ms-2>All Rights Reserved 2025</div>
      </div>
      
      <div class="align-items-center col-lg-4 d-flex flex-column">
        <div class="fs-2 text-center">Redes Sociales</div>
        <div class="align-items-center d-flex gap-5 justify-content-evenly">
          <div>
            <a href=https://www.linkedin.com/in/eduardoherreraf/ target=_blank rel="noopener noreferrer">
              <i class="bi bi-linkedin fs-1"></i>
            </a>
          </div>
          <div>
            <a href=https://github.com/eduardoherreraf target=_blank rel="noopener noreferrer">
              <i class="bi bi-github fs-1"></i>
            </a>
          </div>
          <div>
            <a href=https://www.facebook.com/eduardoherreraforero/ target=_blank rel="noopener noreferrer">
              <i class="bi bi-facebook fs-1"></i>
            </a>
          </div>
          <div>
            <a href=https://twitter.com/ehfeduardo/ target=_blank rel="noopener noreferrer">
              <i class="bi bi-twitter-x fs-1"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
    <div class="align-items-center d-flex gap-2 justify-content-center"></div>
  </footer>
  

  
  <button onclick=topFunction() id=myBtnScroll title="Go to top">
    <svg xmlns:xmlns=http://www.w3.org/2000/svg width=32 height=32 fill=currentColor class="bi bi-arrow-bar-up" style=margin-left:-2px viewBox="0 0 16 16"><path fill-rule=evenodd d="M8 10a.5.5 0 0 0 .5-.5V3.707l2.146 2.147a.5.5 0 0 0 .708-.708l-3-3a.5.5 0 0 0-.708 0l-3 3a.5.5 0 1 0 .708.708L7.5 3.707V9.5a.5.5 0 0 0 .5.5m-7 2.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5"/></svg>
  </button>
  


